ALTER TABLE objeto_detectado
  ADD COLUMN IF NOT EXISTS bbox_x      DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_y      DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_width  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_height DOUBLE PRECISION;
